/// Scene film id → TMDB movie id, pinned so matching is deterministic.
///
/// Generated by `dart run tool/resolve_tmdb.dart` (needs a TMDB token). Films
/// not listed here are matched at runtime by title and year.
const tmdbIds = <String, int>{};
