// Pins a TMDB id for every catalogue film, so the app does not have to
// search at runtime and every match can be reviewed in code review.
//
//   dart run tool/resolve_tmdb.dart            # token from tmdb.json or $TMDB_TOKEN
//
// Writes lib/data/tmdb_ids.dart and prints each match, every miss and every
// runtime that differs from the catalogue by more than 5 minutes.
import 'dart:convert';
import 'dart:io';

import 'package:scene/data/catalogue.dart';
import 'package:scene/data/tmdb.dart';

Future<void> main() async {
  var token = Platform.environment['TMDB_TOKEN'] ?? '';
  final file = File('tmdb.json');
  if (token.isEmpty && file.existsSync()) {
    token = (jsonDecode(file.readAsStringSync()) as Map<String, dynamic>)['TMDB_TOKEN'] as String? ?? '';
  }
  if (token.isEmpty) {
    stderr.writeln('No TMDB token: set TMDB_TOKEN or create tmdb.json {"TMDB_TOKEN": "..."}');
    exit(2);
  }

  final client = TmdbClient(token);
  final ids = <String, int>{};
  final misses = <String>[];
  for (final f in allFilms) {
    final id = await client.findId(f.title, f.year);
    if (id == null) {
      misses.add('${f.id} (${f.title}, ${f.year})');
      continue;
    }
    final info = await client.details(id);
    ids[f.id] = id;
    final runtime = info.runtimeMinutes;
    final flag = runtime != null && (runtime - f.runtimeMinutes).abs() > 5 ? '  ← runtime $runtime vs catalogue ${f.runtimeMinutes}' : '';
    stdout.writeln('${f.id.padRight(20)} → $id  ${info.title} (${info.year})$flag');
  }
  client.close();

  final out = StringBuffer()
    ..writeln('/// Scene film id → TMDB movie id, pinned so matching is deterministic.')
    ..writeln('///')
    ..writeln('/// Generated by `dart run tool/resolve_tmdb.dart` on ${DateTime.now().toUtc().toIso8601String().substring(0, 10)}.')
    ..writeln('/// Films not listed here are matched at runtime by title and year.')
    ..writeln('const tmdbIds = <String, int>{');
  for (final e in ids.entries) {
    out.writeln("  '${e.key}': ${e.value},");
  }
  out.writeln('};');
  File('lib/data/tmdb_ids.dart').writeAsStringSync(out.toString());
  stdout.writeln('\nPinned ${ids.length} of ${allFilms.length}.');
  if (misses.isNotEmpty) stdout.writeln('No confident match: ${misses.join(', ')}');
}
